blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('post/new/', views.post_new, name='post_new'),  # New URL pattern
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    
    path ("accounts/", include('Accounts.urls')),

    #password change
    path("password_change/",auth_views.PasswordChangeView.as_view(), name= "password_change"),
    path("password_change/done",auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    #password reset
    path("password_reset/",auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done",auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(),name = "reset_done"),

    path("blog/", include('blog.urls')),


    path("", include('matrimony.urls'))

    #static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

matrimony/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name= "matrimony"

urlpatterns = [
    
    path('', views.profileviews_list ,name= 'profile_view'),

    #this is the way of passing variable in urls
    path('<int:profile_id>', views.profile_details,name= 'profile_detail'),
    path("contact/", views.contact_us, name = "contact"),
    path("new_profile/", views.newprofileview, name = "new_profile"),
    path('delete_profile/', views.profile_delete_view, name = "profile_delete")
]

matrimony/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
#define the media_route in settings file in core folder
fs = FileSystemStorage(location=settings.MEDIA_ROOT)


class Religion(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self) :
        return self.name
    

class Sect(models.Model):
    name = models.CharField(max_length=100)
    #the many to one relationship b/w sect and religion
    religion = models.ForeignKey(Religion, on_delete=models.CASCADE, related_name="sects")
    def __str__(self) :
        return self.name

class Caste(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self) :
        return self.name
    

class Hobby(models.Model):
    name = models.CharField(max_length=100)
    #we want that the hobby class looks like hobbies in the admin panel so for that purpose we will create this meta class and do the following stuff
    class Meta:
        verbose_name_plural= "Hobbies"


    
    def __str__(self) :
        return self.name
    
    
class FatherProfile(models.Model):
    name = models.CharField(max_length=100)
    occupation= models.CharField(max_length=100,null=True,blank=True)
    def __str__(self) :
        return self.name
        







class profile(models.Model):
    Gender_choice= [('M','Male'),('F','Female')]
    name=models.CharField(max_length=100)
    age=models.IntegerField()
    email=models.EmailField(unique=True)
    profile_pic=models.ImageField(null=True,blank=True)
    gender=models.CharField(max_length=1,choices=Gender_choice)
    occupation= models.CharField(max_length=100,null=True,blank=True)
    birth_date=models.DateField(null=True)
    is_married=models.BooleanField(max_length=1,default=False)
    #here related_name = profile means that it create a list with the name profile in Religion model
    #CASCADE: When an object referenced by a ForeignKey or OneToOneField is deleted, the referencing object is also deleted. This ensures that there are no orphaned objects referencing a non-existing object.
    religion = models.ForeignKey(Religion, on_delete=models.CASCADE, related_name="profile",null=True) 
    sect= models.ForeignKey(Sect, on_delete=models.CASCADE,related_name="sect",null=True)
    caste= models.ForeignKey(Caste, on_delete=models.CASCADE,related_name="caste",null=True)
    #many to many relationship, in many to many relationship we will not use cascade because we dont need to deletethe whole tabble 
    hobby = models.ManyToManyField(Hobby,related_name= "profiles")
    father = models.OneToOneField(FatherProfile,on_delete=models.CASCADE, related_name="dependence",null=True)



    #for the update meesage in the terminal.what we can do is 

    #this syntax will remain same from function defining too super() function and our logic will be written betwwn them
    def save(self,*args,**kwargs):
        print(f'profile is updated for {self.name}') 

        super().save(*args, **kwargs)
    

     #the purpose of this function is to show profile by name instead of profile id
    def __str__(self) -> str:

        return self.name

matrimony/views.py
from django.shortcuts import render,redirect
from .models import profile
from .form import Profileform,NewProfile
#for using formsets we import formset_factory
from django.forms import formset_factory
from django.contrib.auth.decorators import login_required


def profileviews_list(request):
    profiles= profile.objects.all
    user = request.user
    return render(request,"matrimony/profile_view_list.html",{"profiles":profiles,'user':user})

def profile_details(request,profile_id):

    profil= profile.objects.get(id=profile_id)
    user = request.user
    return render(request,'matrimony/profile_detail.html',{"profile":profil,'user':user})

def profile_delete_view(request,profile_id):
    profile_id = profile.objects.get(id = profile_id)
    profile_id.delete()
    redirect( 'matrimony:profile_view')


def contact_us(request):
    
    if request.method== "POST":
        #we are storing the post request data in the vriable of form
        form = Profileform(request.POST)
        if form.is_valid():
            #the cleaned data is the django library that only works when variable pass the validation test
            print(f"NAME: {form.cleaned_data['name']}")
            print(f"EMAIL: {form.cleaned_data['email']}")
            print(f"CONTACT NUMBER: {form.cleaned_data['contact_num']}")
            print(f"MESSAGE: {form.cleaned_data['message']}")
    else:
        form = Profileform

    return render(request,'matrimony/contact.html',{"form":form})

'''def newprofileview(request):
    
    if request.method == "POST":
        #we are storing the post request data in the vriable of form
        form = NewProfile(request.POST , request.FILES)
        if form.is_valid():
            #form.save function only works with modelforms 
            form.save()
            #when you want to redirect to any page so for that you need to specify the name of the page that you write in url file
            return redirect('matrimony:profile_view')
    else:
        form = NewProfile()

    return render(request,'matrimony/new_profile.html',{"form":form})'''


# Create your views here.


# use of Formsets
#we are using this login required decorator for the restriction in our website so user need to login first before filling the form
@login_required
def newprofileview(request):
    #here extra represent the number of forms in one page
    profile_formset = formset_factory(NewProfile , extra=1)
    
    if request.method == "POST":
        #we are storing the post request data in the vriable of form
        formset = profile_formset(request.POST , request.FILES)
        if formset.is_valid():
            #formset is actually works in list form like it save our form in list so we need to use for loop here for saving changes on multiple forms in one page
            for form in formset:
                if form.has_changed():
                    form.save()
            return redirect('matrimony:profile_view')


             
            
            #when you want to redirect to any page so for that you need to specify the name of the page that you write in url file
            #return redirect('matrimony:profile_view')
    else:
        formset = profile_formset
    
    user = request.user

    return render(request,'matrimony/new_profile.html',{"formset":formset,'user':user})

matrimony/templates/matrimony/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1> contact us </h1>
    <form method="post">
        <div class = 'form-group'>
            {{form.name.label_tag}}
            <input type="text" class = 'form-control' name = '{{form.name.name}}'>
        </div>

        <div class = 'form-group'>
            {{form.email.label_tag}}
            <input type="email" class = 'form-control'  name = '{{form.email.name}}'>
        </div>

        <div class = 'form-group'>
            {{form.verify_email.label_tag}}
            <input type="email" class = 'form-control' name = '{{form.verify_email.name}}'>
        </div>

        <div class = 'form-group'>
            {{form.contact_num.label_tag}}
            <input type="text" class = 'form-control' name = '{{form.contact.name}}'>
        </div>

        <div class = 'form-group'>
            {{form.Message.label_tag}}
            <textarea class = 'form-control' name = '{{form.Message.name}}'></textarea>
        </div>
    
           
           {% csrf_token %}
           <input type="submit"  class = 'btn btn-primary'>

    </form>
{% endblock %}

matrimony/templates/matrimony/new_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    
</style>
<h1> Add  a new profile here </h1>
<!--we use the enctype b/c our form can read the media files too-->
    <form method="post" enctype="multipart/form-data">
        {%csrf_token %}
     <!--   {{ form.as_p }}-->
     <!--this is for using formset in django here form represent the formset and f represent the form-->
        
        {{formset.management_form}}
        {%for form in formset%}
            {{ form.as_p }}
        {%endfor%}




    <input type="submit"  class = 'btn btn-primary'>

    </form>
{% endblock %}

matrimony/templates/matrimony/profile_detail.html
{% extends 'base.html' %}   
{% load static %}
{% block content %}
<title>profile views</title>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{{ profile.profile_pic.url }}" class="card-img" alt="Profile picture">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ profile.name }}</h5>
                            <p class="card-text"><small class="text-muted">{{ profile.age }} years old</small></p>
                            <p class="card-text">{{ profile.bio }}</p>
                            <p class="card-text">
                                <strong>Occupation:</strong> {{ profile.occupation }}<br>
                                <strong>Date of Birth:</strong> {{ profile.birth_date }}<br>
                                <strong>Marital Status:</strong> {{ profile.is_married|yesno:"Married,Single" }}<br>
                                <strong>Email:</strong> {{ profile.email }}<br>
                                <strong>Religion:</strong> {{ profile.religion }}<br>
                                <strong>Sect:</strong> {{ profile.sect }}<br>
                                <strong>Caste:</strong> {{ profile.caste }}<br>
                                <strong>Hobbies:</strong> 
                                <ul>
                                {%for hoby in profile.hobby.all%}
                                <li>{{hoby}}<br></li>
                                {%endfor%}
                                
                                </ul> 
                                <strong>Father Name:</strong> {{ profile.father.name }}<br>
                                <strong>Father Occupation:</strong> {{ profile.father.occupation}}<br>
                            </p>
                            <a href="{% url 'matrimony:profile_view' %}" class="btn btn-primary">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

matrimony/templates/matrimony/profile_view_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">

    <a href="{% url 'matrimony:new_profile'%}" class="btn btn-warning">Add Profile</a>
    <hr>
    <div class="row">
        {% for profile in profiles %}
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="{{ profile.profile_pic.url }}" alt="Profile picture" width="100" height="200">
                <div class="card-body">
                    <h5 class="card-title">{{ profile.name }}</h5>
                    <a href="{% url 'matrimony:profile_detail' profile.id %}" class="btn btn-primary">View Profile</a>
                </div>
            </div>
            <p></p>
        </div>


        {% endfor %}
    </div>
</div>
{% endblock %}