Accounts/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name= "Accounts"

urlpatterns = [
    
    path('register/', views.register ,name= 'register'),

    
    path('login/', views.login_view,name= 'login'),
    path('logout/', views.logout_view,name= 'logout'),
    path('delete/', views.delete_view,name= 'delete')

]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('post/new/', views.post_new, name='post_new'),  # New URL pattern
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    
    path ("accounts/", include('Accounts.urls')),

    #password change
    path("password_change/",auth_views.PasswordChangeView.as_view(), name= "password_change"),
    path("password_change/done",auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    #password reset
    path("password_reset/",auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done",auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(),name = "reset_done"),

    path("blog/", include('blog.urls')),


    path("", include('matrimony.urls'))

    #static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

Accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    Gender_choices = [
        ("M","Male"),
         ("F","Female")
    ]
    gender = models.CharField(max_length=1, choices=Gender_choices)


# Create your models here.

Accounts/views.py
from django.shortcuts import render,redirect

from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login, authenticate,logout
from .form import Registrationform
from django.contrib import messages
from django.http import JsonResponse

# Create your views here.

def register(request):
    if request.method== 'POST':
       
        form=Registrationform(request.POST)
        
        if form.is_valid():
            
            form.save()
            return redirect('Accounts:login')
    else:
        form = Registrationform()

    return render(request,'Accounts/register.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        
        if form.is_valid():
            
            user = form.get_user()
            login(request, user)
            return redirect('matrimony:profile_view')
            
    else:
        form = UserCreationForm()

    return render(request,'Accounts/login.html',{"form":form})


def logout_view(request):
    logout(request)
    if request.method == "POST":
        return JsonResponse({'success':True})
    return redirect('Accounts:login')
    
    

def delete_view(request):
    request.user.delete()
    messages.success(request, "Your account is deleted successfully")
    return redirect("Accounts:login")
    

    
    

Accounts/templates/Accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>Account Login</h1>
    <form method="post">

        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Login</button>
    </form>


    <a href="{% url 'password_reset' %}">Forgot Password?</a>

    <p>Do not have an Account?</p>
    <a href="{% url 'Accounts:register' %}">Register Here</a>
{% endblock %}

Accounts/templates/Accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h1> Register your account </h1>
<!--we use the enctype b/c our form can read the media files too-->
    <form method="post" >
        {%csrf_token %}
        {{ form.as_p }}
        
        
      
     <!--   {{ form.as_p }}-->
     <!--this is for using formset in django here form represent the formset and f represent the form-->
     




    <button type="submit"  class = 'btn btn-primary'>Register</button>

    <h1> Already register?</h1>
    <a href=" {%url 'Accounts:login'%}">login here</a>

   



    </form>

    
{% endblock %}