Accounts/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name= "Accounts"

urlpatterns = [
    
    path('register/', views.register ,name= 'register'),

    
    path('login/', views.login_view,name= 'login'),
    path('logout/', views.logout_view,name= 'logout'),
    path('delete/', views.delete_view,name= 'delete')

]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('post/new/', views.post_new, name='post_new'),  # New URL pattern
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    
    path ("accounts/", include('Accounts.urls')),

    #password change
    path("password_change/",auth_views.PasswordChangeView.as_view(), name= "password_change"),
    path("password_change/done",auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    #password reset
    path("password_reset/",auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done",auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(),name = "reset_done"),

    path("blog/", include('blog.urls')),


    path("", include('matrimony.urls'))

    #static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

matrimony/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name= "matrimony"

urlpatterns = [
    
    path('', views.profileviews_list ,name= 'profile_view'),

    #this is the way of passing variable in urls
    path('<int:profile_id>', views.profile_details,name= 'profile_detail'),
    path("contact/", views.contact_us, name = "contact"),
    path("new_profile/", views.newprofileview, name = "new_profile"),
    path('delete_profile/', views.profile_delete_view, name = "profile_delete")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- Load Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'matrimony/css/style.css' %}">
    <title>Matrimonial App</title>
</head>
<body>
    {% include 'header.html' %}

    <p></p>
    
    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main>

    {% include 'footer.html' %}
    
    <!-- Load Bootstrap JS -->
    
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/footer.html
<footer class="footer bg-dark mt-5 fixed-bottom">
  <div class="container">
    <span class="text-muted text-center d-block">© 2023 Matrimonial App</span>
  </div>

templates/header.html
<!-- templates/header.html -->
{% load static %}



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"><img src=" {% static 'images/xloop-logo.png' %}" width = "60px" >Matrimonial App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'matrimony:profile_view' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'matrimony:contact' %}">Contact Us</a>
      </li>

    
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:post_list' %}">My Blogs</a>
      </li>
    </ul>

      {% if user.is_authenticated %}

      <ul id = 'logged_in' class = 'navbar-nav ml-auto'>
        <li class ="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role = 'button', data-toggle = dropdown href="{% url 'password_change' %}">{{ user.username }}</a>
          <div class = 'dropdown-menu dropdown-menu-right'>
          <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
          <a class="dropdown-item" href="{% url 'Accounts:delete' %}">Delete Account</a>
          <a class="dropdown-item" id = 'logout-btn' href="{% url 'Accounts:login' %}">Logout</a>
        
        
          </div>
        </li>
     </ul>
      {%endif%}
    
  </div>
</nav>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  var csrftoken = '{{ csrf_token }}';
</script>
<script src= {% static 'js/header.js' %}></script>